version: "3.4"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - node
    ports:
      - "80"
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
      #      HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  node:
    image: node:18
    command: npm start
    networks:
      - app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DB_HOST=json-server
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"

  json-server:
    image: node:18
    command: npm run server
    ports:
      - "3004:3004"
    networks:
      - app
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated
