services:
  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app
      - frontend
    depends_on: !reset []
    ports:
      - '8080'
    volumes:
      - ./.docker/templates:/etc/nginx/templates:ro
      - .:/app
    environment:
      NGINX_WEB_ROOT: /app
      NGINX_PORT: 8080
      NGINX_MAX_BODY_SIZE: 5M
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
#      HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  node:
    image: node:20
    command: npm run start
    working_dir: /app
    ports:
      - '3000'
    networks:
      - app
      - frontend
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.services.node_${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"
      - "traefik.http.routers.node_${COMPOSE_PROJECT_NAME}-http.rule=Host(`node_${COMPOSE_DOMAIN}`)"
      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
