on:
  push:
    tags:
      - '*.*.*'

name: Create Github Release

permissions:
  contents: write

env:
  COMPOSE_USER: runner
  VITE_APP_API_BASE: https://api.podwalk.itkdev.dk
  VITE_APP_API_ROUTE: /api/v1/

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer install
        run: |
          docker network create frontend
          docker compose run --rm --user=root node npm install
          docker compose run --rm --user=root node npm run build

      - name: Make assets dir
        run: |
          mkdir -p ../assets

      - name: Make assets dir
        run: |
          sudo rm -rf node_modules

      - name: Create archive
        run: |
          sudo chown -R runner:runner ./
          tar --exclude='.git' -zcf ../assets/${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz ./

      - name: Create checksum
        run: |
          cd ../assets
          sha256sum ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz > ../assets/checksum.txt

      - name: Create a release in GitHub and uploads assets
        run: gh release create ${{ github.ref_name }} --verify-tag --generate-notes ../assets/*.*
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
